name: Deploy to İlkbyte Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: connect pull deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            source $NVM_DIR/nvm.sh
            export PATH=$NVM_DIR/versions/node/v22.17.0/bin:$PATH
            cd /root/testv1
            git pull origin main
            npm install
            npm run build
            pm2 startOrReload ecosystem.config.js --update-env
